name: General Suggestion
description: Share feedback, ideas, or anything else
title: "[Suggestion] "
labels: ["suggestion"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea or suggestion? We'd love to hear it!

  - type: textarea
    id: suggestion
    attributes:
      label: Your Suggestion
      description: What would you like to share or suggest?
      placeholder: Tell us your thoughts...
    validations:
      required: true

  - type: input
    id: contributor
    attributes:
      label: Your Name or Handle (optional)
      placeholder: e.g., "@username" or "Anonymous"
    validations:
      required: false
